export interface Activity {
  id?: string; // Optional since it's generated by the backend
  name: string;
  description: string;
  category: string;
  date: Date; // Ensure correct date format
  time: string;
  location: string;
  status: 'PLANIFIEE' | 'EN_COURS' | 'TERMINEE' | 'ANNULEE'; // Adjusted based on backend Status enum
  // Add other fields as needed
}
