export interface ChallengeSubmission {
  id?: string; // optional because it will be generated by the backend
  challengeId: string;
  candidateEmail: string;
  answers: { [key: string]: string }; // key is question/task index or identifier
  passed: boolean;
  submittedAt: string; // ISO format, handled as string in Angular
}