export enum status {
    DONE = ' DONE',
    IN_PROGRESS= ' IN_PROGRESS',
    NOT_SUBMITTED = 'NOT_SUBMITTED',
    PASSED = 'PASSED',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    PENDING = 'PENDING',
}
